// <auto-generated />
using System;
using Kantor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kantor.Migrations
{
    [DbContext(typeof(NbpDbContext))]
    [Migration("20200721164331_NbpDbMigration")]
    partial class NbpDbMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Kantor.Models.NbpCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Average")
                        .HasColumnType("REAL");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<double>("Deviation")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStape")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NbpCurrencys");
                });
#pragma warning restore 612, 618
        }
    }
}
